export const TOPICS = [
  { id: 1, name: "Türkçe dil bilgisi", count: 5 },
  { id: 2, name: "Yönetimde İnsan İlişkileri ve iletişim", count: 2 },
  { id: 3, name: "Yönetim, liderlik ve organizasyon", count: 3 },
  { id: 4, name: "İnsan hakları ve demokrasi", count: 1 },
  { id: 5, name: "Yönetimde etik", count: 1 },
  { id: 6, name: "Türk idare sistemi", count: 2 },
  { id: 7, name: "Protokol kuralları", count: 1 },
  { id: 8, name: "Atatürk İlkeleri ve İnkılap Tarihi", count: 2 },
  { id: 9, name: "Genel kültür", count: 5 },
  { id: 10, name: "T.C. Anayasası", count: 5 },
  { id: 11, name: "657 sayılı Devlet Memurları Kanunu", count: 4 },
  { id: 12, name: "1739 sayılı Milli Eğitim Temel Kanunu", count: 4 },
  { id: 13, name: "222 sayılı İlköğretim ve Eğitim Kanunu", count: 4 },
  { id: 14, name: "652 sayılı KHK", count: 1 },
  { id: 15, name: "4483 sayılı Memurlar ve... Yargılanması Hakkında Kanun", count: 2 },
  { id: 16, name: "5018 sayılı Kamu Mali Yönetimi ve Kontrol Kanunu", count: 3 },
  { id: 17, name: "2886 sayılı Devlet İhale Kanunu", count: 2 },
  { id: 18, name: "4734 sayılı Kamu İhale Kanunu", count: 2 },
  { id: 19, name: "4735 sayılı Kamu İhale Sözleşmeleri Kanunu", count: 1 },
  { id: 20, name: "4982 sayılı Bilgi edinme Hakkı Kanunu", count: 1 },
  { id: 21, name: "5442 sayılı İl İdaresi Kanunu", count: 3 },
  { id: 22, name: "4688 sayılı Kamu Görevlileri Sendikaları ve Toplu Sözleşme Kanunu", count: 3 },
  { id: 23, name: "5580 sayılı Özel Öğretim Kurumları Kanunu", count: 3 },
];
